# Generated by Django 5.1.4 on 2024-12-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterUsage',
            fields=[
                ('date', models.DateField(help_text='Date of water usage.', primary_key=True, serialize=False, verbose_name='Date')),
                ('gallons', models.DecimalField(decimal_places=5, help_text='Amount of water usage in gallons on the date.', max_digits=10, verbose_name='Gallons')),
            ],
            options={
                'verbose_name': 'Water Usage',
                'verbose_name_plural': 'Water Usage',
                'db_table': 'usage',
                'ordering': ('date',),
                'managed': True,
            },
        ),
    ]
